name: pdf_downloader

on:
  workflow_dispatch:
    inputs:
      max_dt:
        description: "max_dt"
        required: false
        default: "1"
  schedule:
    - cron: "*/30 * * * *"
jobs:
  pdf_downloader:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nuuuwan/lk-acts-image:latest

    steps:
      - name: "⬇️ Checkout lk_police_docs:main (READ-ONLY)"
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: "lk_police_docs"
          token: "${{ secrets.REPO_DATA_TOKEN }}"
          fetch-depth: 1

      - name: "⬇️ Checkout lk_police_docs:data"
        uses: actions/checkout@v4
        with:
          repository: nuuuwan/lk_police_docs
          ref: "data"
          path: "lk_police_docs_data"
          token: ${{ secrets.REPO_DATA_TOKEN }}
          fetch-depth: 1

      - name: "⚙️ Run pdf_downloader"
        run: |
          cd lk_police_docs;
          export PYTHONPATH="$PYTHONPATH:./src"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

          git pull --rebase origin main
          python workflows/pdf_downloader.py ${{ github.event.inputs.max_dt }}

      - name: "⬆️ Push lk_police_docs:data"
        run: |
          cd lk_police_docs_data;
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit in lk_police_docs:data."
            exit 0
          fi
          git commit -m "🤖 [pdf_downloader.yml] $(date '+%Y-%m-%d-%H%M')"
          git pull --rebase origin data
          git push origin data
